In [1]:
import numpy as np
x = np.arange(12)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [2]:
print(x.shape)

(12,)


In [3]:
# 得到实例中元素(element)的总数
print(x.size)

12


In [6]:
X = x.reshape((3, 4))
print(X)
# 由于x的元素个数是已知的，这里的-1是能够通过元素个数和其他维度的大小推断出来的
X1 = x.reshape((3, -1))
print(X1)
X2 = x.reshape((-1, 4))
print(X2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [9]:
np.zeros((2, 3, 4))
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
# Turn list into a numpy array
Y = np.array([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
print(Y)
# 创建随机数组，他的每个元素都随机采样于均值为0，标准差为1的正态分布
Z = np.random.normal(0, 1, size=(3, 4))
print(Z)

[[2 1 4 3]
 [1 2 3 4]
 [4 3 2 1]]
[[ 1.88731118  1.83480181  0.51143404  0.78867643]
 [ 0.25346417 -0.27538444  1.37062941  0.28601899]
 [ 0.85422625  0.19912149 -0.91290865 -0.62048988]]


In [ ]:
# 按元素乘法
X * Y
# 按元素除法
X / Y
# 按元素做指数运算
Y.exp()
# dot 做矩阵乘法，需要维数match

In [26]:
# 多个矩阵连接(concatenate) 行上维数为0，
np.concatenate((X,Y), axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 2,  1,  4,  3],
       [ 1,  2,  3,  4],
       [ 4,  3,  2,  1]])

In [28]:
# 列上维数为1
np.concatenate((X,Y),axis=1)

array([[ 0,  1,  2,  3,  2,  1,  4,  3],
       [ 4,  5,  6,  7,  1,  2,  3,  4],
       [ 8,  9, 10, 11,  4,  3,  2,  1]])

In [29]:
# 使用条件判断是可以得到元素为0或者1的新的np.array
X == Y

array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [30]:
X.sum()

66

In [34]:
# Broadcasting 广播机制是numpy规定的，如果两个不匹配matirx做运算进行的维数匹配(复制来达到能够计算的维数)
A = np.arange(3).reshape((3,1))
B = np.arange(2).reshape((1,2))
print(A)
print(B)
A + B

[[0]
 [1]
 [2]]
[[0 1]]


array([[0, 1],
       [1, 2],
       [2, 3]])